<?php

/**
 * @file
 * Installation functions for Dependency Injection module.
 */

/**
 * Implements hook_install().
 */
function inject_install() {
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('type', 'module')
    ->condition('name', 'inject')
    ->execute();
}

/**
 * Implements hook_uninstall().
 */
function inject_uninstall() {
  variable_del('inject_dump');
  variable_del('inject_compile');
}
